### PR TITLE
Create Metagraph from Dataframe Constructor

### LINKED ISSUE #17: Utility for making MetaGraph from DataFrame
This something worth trying to integrate into library? Takes DataFrame edgelist (where entries can be names or strings, not necessarily sequential vertex ids) and returns MetaGraph. Obviously some places for generalization (directed versus undirected; edge attributes; etc.)

```
function create_metagraph_from_df(df, origin, destination)

    # Map node labels to indices
    nodes = [df[origin]; df[destination]]
    nodes = unique(nodes)
    sort!(nodes)

    vertex_names = DataFrame(Dict(:name => nodes))
    vertex_names[:vertex_id] = 1:nrow(vertex_names)

    # Merge in to original
    for c in [origin, destination]
        temp = rename(vertex_names, :vertex_id => Symbol(c, :_id), :name => c)
        df = join(df, temp, on=c)
    end

    g = DiGraph(nrow(vertex_names))
    mg = MetaDiGraph(g)
    for r in eachrow(df)
        add_edge!(mg, r[Symbol(origin, :_id)], r[Symbol(origin, :_id)])
    end

    for r in eachrow(vertex_names)
        set_prop!(mg, r[:vertex_id], :name, r[:name])
    end

    return mg
end
```

### PR DESCRIPTION
**Pull request by nickeubank**
Most social scientists I work with live in a tabular data world, so I do this a lot, and assume others might also appreciate the utility. Input welcome on both content and placement in code. 

Relatedly: is there a way to do optional dependencies? Something one needs to run tests but don't require for package? Don't want to add `DataFrames` as full dependency, but need to test. 

closes #17

### CODE REVIEW

**Comment by sbromberger** [comment]
~~I'm not entirely happy with adding a dependency on DataFrames here. It might make more sense to put it in GraphIO but am open to arguments for/against any alternative.~~

Edited to add: you can add a REQUIRES into the `test/` directory and that will only make a requirement for tests. This might actually be a good approach. Would you mind testing it?

**Comment by nickeubank** [comment]
@sbromberger Perfect! Yeah, I agree  -- don't want this as a real dependency. I was thinking it'd be great to have something that works like Python libraries with "optional" dependencies, that do additional things if a library is available, but doesn't require. 

The problem I hit is that I get `DataFrame not defined` when I try and import the module (`using MetaGraphs`) if I don't have `using DataFrames` at the top of `MetaGraphs.jl`. Any idea how to get around this?

**Comment by sbromberger** [comment]
Argh. That's right. The only way I know to get around this is with Requires.jl, but that breaks horribly if there are macros in the dependent package.

Maybe for now you could make a separate package for this, and we could move it to JuliaGraphs so that if people needed DataFrames integration with MG, they could import both?

This would also allow (require) you to be the package maintainer :)

**Comment by nickeubank** [comment]
Been thinking about this, and seems like this is a pretty small thing to be it's own package. [Asked on discourse](https://discourse.julialang.org/t/optional-dependencies/8029), and sounds like [this library](https://github.com/MikeInnes/Requires.jl) is the current best solution -- thought on using it for this function?

**Comment by sbromberger** [comment]
Responded on discourse. :)

**Comment by sbromberger** [comment]
You know, perhaps this is better off in LightGraphsExtras, or we start a MetaGraphExtras?

**Comment by nickeubank** [comment]
Yeah, that seems a better solution. It may start alone, but probably won't stay that way. 

We could start a `MetaGraphExtras`, or move to a `GraphExtras` that covers both?

**Comment by sbromberger** [comment]
I hate the thought of this going into a "dumping ground" repo. :( It is a small thing, but let's consider a standalone package.

**Comment by nickeubank** [comment]
OK, i'll play around with it a little. What's best way to get it under JuliaGraphs? Start under my account then change ownership later?

**Comment by sbromberger** [comment]
> What's best way to get it under JuliaGraphs?

The way I do it is start it under my own account and then transfer it. I can then set you up as the repo maintainer/owner.

**Comment by sbromberger** [comment]
Closed - see https://github.com/JuliaGraphs/MetaGraphs.jl/issues/17#issuecomment-354380258

**Pull request closed without merging**
