### PR TITLE
Pared down

### PR DESCRIPTION
**Pull request by bramtayl**
This is probably a no-go for compatibility reasons, but I had need for MetaGraphs and the type-stability things was bothering me, so I made my own pared down version with type-stable metadata.

### CODE REVIEW

**Comment by sbromberger** [comment]
@bramtayl I'm interested in this, but what incompatibilities are you introducing?

(Also, we have merge conflicts now.)

**Comment by bramtayl** [comment]
Pretty darn breaking, but I like the indexing syntax. Look at the new docstring for MetaGraph to see some doctest examples.

**Comment by sbromberger** [comment]
I like this idea - the type instability of the current structure always bothered me.

My recommendation would be to make this its own package, and eventually we could deprecate MetaGraphs.jl to this code.

**Comment by jpfairbanks** [comment]
Why deprecate the dictionary based approach? I think that both approaches can coexist. Some applications will have vertices with heterogeneous metadata and you will want to have a dictionary based approach, many more applications will have homogeneous metadata and the type stable approach is better. 

I can see for example implementing GraphQL in such a way that you returned the query result as a MetaDiGraph. In this case if you returned fully typed data instead of the current Dictionary based approach, potentially every query would return a different type of graph, which would mean a lot of compiling, with additional compile time overhead exceeding the runtime cost savings.

I'm happy to see a more strongly typed MetaGraph implementation, I just don't think we need to deprecate the existing implementation (in fact that would cause breakage in my GraphViz via julia workflow).

**Comment by sbromberger** [comment]
> Why deprecate the dictionary based approach? 

I don't think it would be explicit - just that we would see a general migration to the new type-stable package.

**Comment by bramtayl** [comment]
Worth noting that you can use my branch pretty easily if you want type instability: just set `AtVertex` and `AtEdge` to `Any`.

**Comment by bramtayl** [comment]
What should I call the new package?

**Comment by sbromberger** [comment]
> What should I call the new package?

@jpfairbanks given https://github.com/JuliaGraphs/MetaGraphs.jl/pull/88#issuecomment-557657237, is there any reason not to just freeze 0.6.x with a final release and move this to, say, 0.7.0? We're < 1.0 so we can tolerate breaking changes but we should tag a final release of the old behavior given that lots of people are using it.

We can also post on discourse.

**Comment by bramtayl** [comment]
Verdict?

**Comment by sbromberger** [comment]
My position hasn't changed: I think we should cut a final 0.6.x release, merge this, release it as 0.7.0, and post to discourse that folks should test their code against this before upgrading.

**Comment by bramtayl** [comment]
Yay! Let me know how I can help

**Comment by sbromberger** [comment]
@bramtayl - can you do me a favor and create a clean version of this (once #94 is merged, perhaps?) I'll figure out how to tag a new release based on the PR at that point, and we'll bump this as 0.7.0.

**Comment by bramtayl** [comment]
Sure. I'll wait for #94 to be merged

**Comment by sbromberger** [comment]
Oh, also, you'll want to get code coverage up a bit :)

**Comment by sbromberger** [comment]
@bramtayl it's all yours. Let me know when you're ready and we'll get a Discourse notification out.

**Comment by sbromberger** [comment]
Ref: https://discourse.julialang.org/t/ann-metagraphs-major-changes-coming/33992

**Comment by bramtayl** [comment]
See #97

**Pull request closed without merging**
