### PR TITLE
Extend add_vertex! and add_edge!

### PR DESCRIPTION
**Pull request by leclere**
Add methods to add_vertex! and add_edges! to accept properties as arguments. Properties can be given with symbol, value argument or Dict argument.

### CODE REVIEW

**Comment by sbromberger** [comment]
@leclere - if you want to fix this up I'll do a final review and merge it. Thanks.

**Comment by leclere** [comment]
@sbromberger It's all right for me. Thanks for your review.

**Comment by jpfairbanks** [comment]
Hi @leclere, what does "It's all right for me" mean?

**Comment by leclere** [comment]
Hello @jpfairbanks , 

I didn't see that the commit from @sbromberger  broke some test. It was mainly due to some function not returning boolean as LightGraphs standard. The test should pass now. 

Unfortunately I do not know where is the coverage loss. Furthermore I have some trouble with my local version of MetaGraph.

**Comment by sbromberger** [comment]
@leclere 
> Furthermore I have some trouble with my local version of MetaGraph.

Is this something we can help with?

**Comment by leclere** [comment]
@sbromberger No. I just reinstalled the master version without problem. 

Do you want to have a better test coverage of the diff ?
If yes I have two questions:
- is there an easy way to identify non-covered functions
- is there an easy way, like with Pkg.checkout, to take my local version to this branch ? Or should I git clone ?

**Comment by jpfairbanks** [comment]
To find uncovered lines use the codecov website by clicking the "details" link next to codecov/patch. Here is the link for convenience. https://codecov.io/gh/JuliaGraphs/MetaGraphs.jl/compare/72d93ec7f37403f78edfd025cf5fceb4e9cf5bc8...b34d486648ffd5d09c1b2c1b815ee41792fd6779/diff

`Pkg.checkout("PackageName", "branchname")`

**Comment by sbromberger** [comment]
Thank you for this PR, @leclere !

**Pull request merged**
